version: '3.9'

services:
  app:
    build: .
    container_name: cinema-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - broker
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev

  db:
    image: postgres:15
    container_name: cinema-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: cinema
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cinema-redis
    ports:
      - "6379:6379"

  broker:
    image: rabbitmq:3-management
    container_name: cinema-broker
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db-data:
